name = "haishuyoufun"
account_id = "e6b96ab1c6d389ad7fb6584810573128" # Yunhairichu@gmail.com 的账户ID
workers_dev = true
compatibility_date = "2023-10-30"
main = "worker.js"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
name = "haishuyoufun-prod"
routes = ["haishuyoufun.com/*", "www.haishuyoufun.com/*"]

# 如果您使用KV存储静态资源
# [kv_namespaces]
# ASSETS = "your_kv_namespace_id"