name = "haishuyoufun"
type = "webpack"
account_id = "yunhairichu@gmail.com" # 请替换为您的Cloudflare账户ID
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-10-30"

[site]
bucket = "./dist"
entry-point = "worker.js"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "haishuyoufun-prod"
route = "haishuyoufun.com/*"
zone_id = "your_zone_id" # 请替换为您的域名区域ID

# 如果您使用KV存储静态资源
# [kv_namespaces]
# ASSETS = "your_kv_namespace_id"